name = "Quoridor"
uuid = "314f219f-e625-4635-812a-5cdb0e2e016c"
authors = ["roolio"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
